name: "Create a release after pushing a tag"
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # matches numeric tags like 1.2.5

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4.0.0
      - name: Lint
        run: pnpm run lint
      - name: Build
        run: pnpm install && pnpm build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            main.js
            manifest.json
